### ISSUE TITLE
Dockeriser le bouzin

### ISSUE THREAD

**Issue by rqueraud** [pixel-ports/pas_modelling#10]

**Comment by erwan-simon-CATIE** [comment]
Etrangement, avec le Dockerfile présent, j'ai un problème à l'appel de pip (pr installer les requirements): /bin/sh: 1: pip: not found

**Comment by erwan-simon-CATIE** [comment]
Il faut changer le cwd avant ds lancer RUN pip install --requirement "./DOCKERISATION/requirements.txt"
 ?
