### ISSUE TITLE
Integration of the model in the OT

### ISSUE THREAD

**Issue by rqueraud** [pixel-ports/pas_modelling#3]
Hi @benmomo ,

With @ES-catie , we were wondering if we have to put the Docker Image in some registry ? And if so, how do we access the registry that you are using ? 

Otherwise, how is the OT listing all the models ?

**Comment by benmomo** [comment]
Hi @rqueraud , 
you have already an account at https://hub.docker.com/orgs/pixelh2020 where you can upload your Docker images.
This registry is public, but you can also use private repos if you want; in that case you will have to introduce credentials when the model is published through the OT

**Comment by rqueraud** [comment]
Thanks for the answer, I forgot that I had access to this registry.

My question is more related to : "Where **should** I put my image ?" than "Where **can** I put my image ?".

In addition, from the OT, how do you list all the available models ? Is that a hard-coded list ?

**Comment by benmomo** [comment]
Hi again,
- dockerhub/pixelh2020 is public, you can put it directly there if you are going to release PAS-energy completely as open source. No folder structure/hieraerchy is defined. You can already find there a lot of images
- if there is some IP issue with your code, then you should work with a private repo
- OT does not list any models unless they have been published. It does not connect anywhere unless explicitly told during the publication process. Theoretically you should use the dashboard, but you can use the OT-UI for testing. In Filabs you can test, for the PIXEL platform in FRBOD I don't know, as I don't have access to it (theoretically Marc installed everyhing there and it seemed to work)

**Comment by rqueraud** [comment]
What do you mean by "publish the model" and the "publication process" ? Can I find documentation about that ?

**Comment by benmomo** [comment]
Yes, info available in D6.4 and also online (https://docs-hub-ot.readthedocs.io/en/latest/user_guide/#graphical-user-interface). Tomaz (XLAB) was able to publish his PARES_model in Filabs last week  (I suppose you have an account, otherwise ask PRO). But you may test it in FRBOD. I think the Dashboard also has its own UI that maps to the OT API, but never tested it (PRO did)

**Comment by rqueraud** [comment]
Ok thanks, that's exactly what I was looking for !
